calculadora_binaria/calc/urls.py
from django.urls import path
from .views import CalcBinView, ResultView

app_name = "calc"

urlpatterns = [
    path('', CalcBinView.as_view(), name="calculadora_binario"),
    path('resultado/', ResultView.as_view(), name="result")
]

calculadora_binaria/calc/models.py
from django.db import models

class Calculo(models.Model):
    sentenca = models.CharField(max_length=255)

    def __str__(self):
        return self.sentenca

calculadora_binaria/calc/forms.py
from django import forms
from .models import Calculo

class CalcBinForms(forms.ModelForm):
    class Meta:
        model = Calculo
        fields = ["sentenca"]

calculadora_binaria/calc/views.py
import django
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from .forms import CalcBinForms
from .models import Calculo
from .functions_bin import *

# Create your views here.

class CalcBinView(CreateView):
    template_name = "calc/calculator.html"
    model = Calculo
    form_class = CalcBinForms
    context_object_name = "calculadora"
    success_url = reverse_lazy("calc:result")

class ResultView(TemplateView):
    template_name = "calc/result.html"

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        ultima = len(Calculo.objects.all())

        sentenca = Calculo.objects.filter(id=ultima)[0]
        content["sentenca"] = sentenca
        content["resultado"] = ""

        for elemento in str(sentenca):
            if elemento not in " +-/*01":
                content["resultado"] = "Sentença inválida"
                break
        
        if not content["resultado"]:
            content["resultado"] = resolve_equacao(str(sentenca))

        return content



calculadora_binaria/calc/templates/calc/calculator.html
{% extends 'calc/layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="form">
        <form action="" method="post">
            <legend>Digite a sentença em binário</legend>
            {% csrf_token %}
            {% render_field form.sentenca id+="sentenca" autocomplete+="off" class+="sentenca" placeholder+="Digite a sentença aqui!"%}
            <br>
            <div class="form-button">
                <input class="go-button" type="submit" value="Calcular">
            </div>
        </form>
    </div>

{% endblock %}

calculadora_binaria/calc/templates/calc/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <title>{% block title %} Calculadora binaria {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'calc/style.css' %}">
    <link rel="stylesheet" href="{% static 'calc/reset.css' %}">
    <link rel="stylesheet" href="{% static 'calc/result.css' %}">
</head>
<body>
    <div class="intro">
        <a href="https://ejrgeekio.com/"><img src="{% static 'calc/logo.png' %}" alt=""></a>
        <h1>Calculadora Binária</h1>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

calculadora_binaria/calc/templates/calc/result.html
{% extends 'calc/layouts/base.html' %}

{% block content %}
    <div class="content">
        <h3>Resultado</h3>
        <div class="resultado">
            <p class="sentenca">{{ sentenca }}</p>

            {% if resultado %}
                
                <p class="result">{{ resultado }}</p>

            {% endif %}
        </div>
        <div class="form-button">
            <a href="{% url 'calc:calculadora_binario'%}"><button class="go-button">Nova Senteça</button></a>
        </div>
    </div>


{% endblock %}